133 add alias to layer panel
cartodb-org/cartodb pull request #136
Opened 2017-03-06 20:15 UTC by coyle5280

2017-03-07 16:12 UTC, gfiorav requested changes
Nice!

I have a couple of comments that need to be addressed.

Also, a question: will this happen when you're in dataset view? (i.e. 'Editing Mode')

Thanks!

2017-03-07 16:12 UTC, gfiorav commented on lib/carto/http_header_authentication.rb
> +      puts "user-auto-creation : Trying to extract value from headers for #{header}, value is #{headers[header || '']}"
Don't commit this file! It's on a separate PR, not merged yet :)

2017-03-07 16:12 UTC, gfiorav commented on lib/assets/javascripts/cartodb/table/layer_panel_view.js
> +
I think it's a good idea to never leave two lines empty between statements!

2017-03-07 16:12 UTC, gfiorav commented on lib/assets/javascripts/cartodb/table/layer_panel_view.js
> +          .text(this.table_alias_name || layer.get('table_name_alias') || layer.get('table_name').replace(/_/g,' '));
Interesting! When do these two hold different values?

```js
this.table_alias_name || layer.get('table_name_alias')
```

2017-03-07 16:47 UTC, gfiorav commented on lib/assets/javascripts/cartodb/table/layer_panel_view.js
> +          .text(this.table_alias_name || layer.get('table_name_alias') || layer.get('table_name').replace(/_/g,' '));
If `layer.get('table_name_alias')` points to nothing, we should remove it! 🔥

2017-03-07 16:55 UTC, gfiorav commented
I'm getting an inconsistent behaviour in 'Editing Mode'


## STR:

0. Have a dataset with a table name alias
1. Go into 'Editing Mode' (`/user/<username>/tables/<table name>`)
2. Switch to 'Map'
3. Switch to 'Table'

## Expected result

The panel layer name is the aliased name

## Actual result

The panel layer name reverted to the non-aliased name

2017-03-08 10:58 UTC, gfiorav commented
What's the status on this? Could you reproduce it or fix it?

2017-03-08 20:01 UTC, gfiorav commented
Hey @coyle5280! Please take care of my previous comments and un commit the cdb module!

2017-03-08 20:51 UTC, coyle5280 commented
@gfiorav The cdb module has been rolled back to commit 52b4941 and the cdb file is longer in the PR.

2017-03-09 10:45 UTC, gfiorav approved these changes

2017-03-09 11:13 UTC, merged