149 column rename
cartodb-org/cartodb pull request #155
Opened 2017-03-16 21:06 UTC by coyle5280

This closes #149 

# Changes
Updated `table.js` so that when a data-user renames a column the corresponding alias column name object is updated as well
Updated  `table_header_view.jst.ejs` to handle new logic for column renaming
Updated `tabledata.js` to not place column name in alias field. Alias field is now a null value.
Updated `wizard.js` to handle a null column alias value
Updated `header_view.js` to use alias value as column name if available if not to use original column name. Also added field for original column name so that a datauser can see old and new name.   

# Acceptance
- [ ] Regular user should be able to edit column name if table was owned by user and not a remote or imported table
- [ ] Regular user should only see column name and type.  Column name should reflect alias value if table has been imported and the column has been given an alias. If not user should see original column name.
- [ ] Data-user can see both original and alias column name
- [ ] Data-user can edit both alias column name and original column name
- [ ] Column alias values can only be created or edited in 'Edit Mode'.  
- [ ] Data-user can still see original and alias column names in 'regular mode' but cannot edit alias name only original name
- [ ] If data-user edits a column name and that column has an alias, the new alias key-value is add and the old key-value is removed.

2017-03-17 10:49 UTC, gfiorav requested changes
Let's discuss this approach

2017-03-17 10:49 UTC, gfiorav commented on vendor/assets/javascripts/select2.min.js
> +                            if (query.matcher(term, (element.attr('alias') !== 'undefined') ? element.attr('alias') : element.text(), element)) {
I'm not sure we can modify JQuery library (licensing).

We'll have to use another way :)

2017-03-17 15:15 UTC, gfiorav commented on lib/assets/javascripts/cartodb/models/wizard.js
> +                return (r[2]) ? r[2].toLowerCase() : r[0].toLowerCase();
```js
return (r[2] || r[0]).toLowerCase();
```

2017-03-17 15:52 UTC, coyle5280 commented on lib/assets/javascripts/cartodb/models/wizard.js
> +                return (r[2]) ? r[2].toLowerCase() : r[0].toLowerCase();
This has been updated

2017-03-17 16:34 UTC, gfiorav approved these changes
Thanks!

2017-03-17 20:18 UTC, coyle5280 commented
The changes have been made to correct the alias add vs edit bug that was occurring.  Also I updated the empty alias value to be null and not undefined.  When adding an alias the datauser should now see the add option and not the edit/remove option unless an alias was already added.

2017-03-17 20:18 UTC, coyle5280 commented on lib/assets/javascripts/cartodb/table/header_dropdown.js
> +    this.options.columnAlias = alias;
Removed redundant code.

2017-03-22 15:06 UTC, gfiorav approved these changes
Thanks!

2017-03-22 19:38 UTC, merged