hide sort if no items added to list
cartodb-org/cartodb pull request #201
Opened 2017-10-02 17:30 UTC by coyle5280

This closes #190 

# Context

This PR modifies `selection.js`.  Logic was added to hide sort filter if item count is 0.

# Acceptance

- [ ] User adds selection filter with options that exceed 250+ and sees no sort options.
- [ ] User searches and then adds item to selection and sees sort filter. Sort will be `Default order`.
- [ ] User can change sort type with no issues.
- [ ] User removes all items and sort option will disappear.
- [ ] Sort filter will always default to `Default order`.

2017-10-26 14:07 UTC, gfiorav commented
Closes #188, not #190 I think!

2017-10-26 14:08 UTC, gfiorav requested changes
Just need to remove an extra line!

2017-10-26 14:08 UTC, gfiorav commented on lib/assets/javascripts/cartodb/table/menu_modules/filters/selection.js
> +
Remove this extra line please!

2017-10-30 15:27 UTC, coyle5280 commented
Line removed. Thanks!

2017-10-31 18:06 UTC, gfiorav approved these changes
Thanks!

2017-11-01 18:07 UTC, alissarose approved these changes
looks good in the vm!

2017-11-16 17:08 UTC, merged