Adjust histogram label number abbreviations and rounding
cartodb-org/cartodb pull request #204
Opened 2017-10-04 19:35 UTC by coyle5280

This closes #196 

# Context
This PR modifies `histogram.js`.  A new function is used to calculate the numerical abbreviation and rounding for the histogram.

# Acceptance
- [ ] When a user selects a numerical histogram the displayed values align with BB standards.

2017-10-05 15:41 UTC, gfiorav requested changes

2017-10-05 15:41 UTC, gfiorav commented on lib/assets/javascripts/cartodb/table/menu_modules/filters/histogram.js
> +      var newValue = value = Math.round(value);
Explain that this triple assign is doing please.

If you could break this into a less compact more understandable code it'd be great!

2017-10-05 15:41 UTC, gfiorav commented on lib/assets/javascripts/cartodb/table/menu_modules/filters/histogram.js
> +              var dotLessShortValue = (shortValue + '').replace(/[^a-zA-Z 0-9]+/g,'');
I feel like I need a comment explaining the logic in this method!

2017-10-05 15:41 UTC, gfiorav commented on lib/assets/javascripts/cartodb/table/menu_modules/filters/histogram.js
> +    abbreviateNumber: function (value) {
Please create a small test suite to check this method will perform well under different values (absence or nullity of values included).

2017-10-06 17:13 UTC, coyle5280 commented on lib/assets/javascripts/cartodb/table/menu_modules/filters/histogram.js
>      abbreviateNumber: function (value) {
@gfiorav I added some inline comments to help explain the function. Hope that helps.

2017-10-09 15:27 UTC, gfiorav requested changes
Thanks for the comments! I'm still missing the tests for the abbreviateNumber method.

2017-10-16 15:05 UTC, gfiorav commented
Hey @coyle5280 I just realised it's very hard to run the jasmine suites. Let's forget about that for now.

2017-10-16 15:05 UTC, gfiorav approved these changes

2017-11-01 19:02 UTC, alissarose approved these changes

2017-11-16 17:12 UTC, merged